### ISSUE TITLE
角色面板报错（提供解决方案）

### ISSUE THREAD

**Issue by Chengzivzx** [NotIvny/ark-plugin#7]
### 1. **具体报错**
查看角色面板时后台提示：

```
0|Miao-Yunzai  | [MiaoYz][17:04:32.300][ERRO] [喵喵:角色面板][profileDetail]
0|Miao-Yunzai  | [MiaoYz][17:04:32.301][ERRO] TypeError: Assignment to constant variable.
0|Miao-Yunzai  |     at Object.render (file:///C:/Users/Administrator/Desktop/bot/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileDetail.js:290:24)
0|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Miao-Yunzai  |     at async cls.<computed> [as profileDetail] (file:///C:/Users/Administrator/Desktop/bot/Yunzai-Bot/plugins/miao-plugin/components/App.js:96:18)
0|Miao-Yunzai  |     at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/bot/Yunzai-Bot/lib/plugins/loader.js:275:41)
```
### 2. **解决方案**
找到
```
...\plugins\ark-plugin\backup\miao-plugin-rank\apps\profile\ProfileDetail.js
```
**以及**
```
...\plugins\miao-plugin\apps\profile\ProfileDetail.js
```
并将其文件中287行内容
由
```
          const rankType = ArkCfg.get('RankType', 0)
```
**改为**
```
          let rankType = ArkCfg.get('RankType', 0)
```

**Comment by NotIvny** [comment]
ok

**Comment by NotIvny** [comment]
仓库炸了，目前commit不了
line 289~294先这样改：
```
case 0:
    characterRank = ret.rank
case 1:
    characterRank = ret.percent
case 2:
    characterRank = `${ret.rank} (${ret.percent}%)`
```
